Add controllers
kriulkin/java-shareit pull request #2
Opened 2023-05-07 16:31 UTC by kriulkin

2023-05-08 16:44 UTC, ohelly requested changes
Привет! Отличная работа, все работает корректно. Есть одно небольшое замечание, которое необходимо исправить. Также я оставил ряд рекомендаций, на которые стоит обратить внимание.

2023-05-08 16:44 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  public class Item {
Необходимо добавить еще одно поле - request, на данном этапе пусть типа long, как идентификатор.

2023-05-08 16:44 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +package ru.practicum.shareit.item;
Рекомендация: Все классы будет лучше раскидать по пакетам, Контроллер - в controller, Маппер - в mapper, Сервис - service, Хранилище - storage. Аналогично и для модуля user.

2023-05-08 16:44 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +public class ItemMapper {
Рекомендация: Для создания мапперов рекомендую попробовать такую штуку как mapstruct, очень полезная и в будущем может пригодится.
https://www.baeldung.com/mapstruct

2023-05-08 16:44 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +public class UserService {
Рекомендация: Также рекомендую для сервисов создавать интерфейсы, чтобы классы-реализации его имплементили.

2023-05-08 16:44 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +        return List.copyOf(users.values());
Отлично! Делается копия хранилища

2023-05-08 16:44 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +public class ItemService {
Рекомендация: Аналогичная рекомендация по созданию интерфейса.

2023-05-08 16:44 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private final UserStorage userStorage;
Рекомендация: USerStorage будет лучше заменить на UserService, так как принято, что хранилище напрямую использует только "свой" сервис.

2023-05-08 16:44 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (userStorage.get(userId) == null) {
Рекомендация: Также, если UserStorage заменить на UserService, то данная проверка будет не нужна, так как она уже есть в юзер-сервисе.

2023-05-08 16:44 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (userId != item.getUserId()) {
Необходимо исправить: Если вещь с данным идентификатором не существует, то на текущей строке вылетит NullPointerException при вызове item.getUserId(). Необходимо перед этим проверить, что такая вещь есть.

2023-05-08 16:44 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +    public Item delete(long id) {
Не реализован метод. Если он не используется то его лучше выпилить.

2023-05-10 14:15 UTC, kriulkin commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +package ru.practicum.shareit.item;
некоторые классы уже были в "начальном" репозитории, например, User.java , и он не был упакован в пакет model. Поэтому я оставил классы, которые уже были как есть, а те, которые появились в процессе работы, собрал по пакетам.

2023-05-10 14:17 UTC, kriulkin commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +public class ItemMapper {
попытался инициализировать в mapstruct в pom.xml , и даже не используя его в коде, не смог скомпилировать код . По какой то причине перестают работать аннотации lombok: не смог найти геттеры и сеттеры сущностей. Пока не смог выяснить в чем причина. Похоже, что на это уйдет какое то время

2023-05-11 11:58 UTC, ohelly approved these changes
Привет! Отличная работа, исправлены все замечания. Работу принимаю, можно двигаться дальше. Удачи в дальнейшем обучении!

2023-05-21 10:28 UTC, merged