Add item requests
kriulkin/java-shareit pull request #5
Opened 2023-05-30 12:53 UTC by kriulkin

2023-06-01 11:59 UTC, ohelly requested changes
Привет! Отличная работа, все работает корректно. Есть пара рекомендаций на которые стоит обратить внимание. Также рекомендую, хотя бы поверхностно, изучить транзации и начать применять их в коде. Транзации очень важная тема, про них будут спрашивать на собесах 100%

2023-06-01 11:59 UTC, ohelly commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
>  package ru.practicum.shareit.request;
Рекомендация: Будет лучше вынести контроллер в отдельный пакет - controller, так же как и модель, маппер и репозиторий.

2023-06-01 11:59 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            request = requestStorage.getById(itemDto.getRequestId());
Рекомендация: Метод getById будет лучше заменить на findById и в случае если элемента нет в БД выкидывать исключение
![image](https://github.com/kriulkin/java-shareit/assets/51891976/4af81c92-b97a-46b2-9286-d1567668193f)

2023-06-02 03:13 UTC, kriulkin commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
>  package ru.practicum.shareit.request;
Совсем забыл про транзакции...😬 Обязательно почитаю про них по подробнее. Спасибо!

2023-06-02 07:13 UTC, ohelly approved these changes
Привет! Все супер, работу принимаю. Можно двигаться дальше!

2023-06-07 14:48 UTC, merged