feat: разделить приложение на server и gateway, реализовать запуск в …
kriulkin/java-shareit pull request #6
Opened 2023-06-08 12:55 UTC by kriulkin

…докер

2023-06-08 20:23 UTC, ohelly requested changes
Привет! Отличная работа, все работает корректно. Есть пара рекомендаций, на которые стоит обратить внимание. Их выполнение необязательно

2023-06-08 20:23 UTC, ohelly commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +public class BaseClient {
Рекомендация: Для написания клиентов рекомендую использовать webClient или Feign, с ними придется писать меньше кода и они намного гибче в использовании

2023-06-08 20:23 UTC, ohelly commented on server/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotBlank(message = "Item with empty name", groups = New.class)
Рекомендация: Всю валидацию моделей из модуля server можно смело убирать, так как теперь все модели валидируются в модуле gateway, в севере это теперь просто лишняя проверка

2023-06-09 12:43 UTC, kriulkin commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +public class BaseClient {
Этот класс был предложен в репозитории задания. Но обязательно почитаю про эти.

2023-06-09 12:44 UTC, kriulkin commented on server/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotBlank(message = "Item with empty name", groups = New.class)
Про валидацию вообще забыл....😬

2023-06-10 08:41 UTC, ohelly approved these changes
Привет! Все супер, работу принимаю! Удачи в дальнейшем обучении!

2023-07-14 10:28 UTC, merged